apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pnt-quiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend
              mountPath: /usr/share/nginx/frontend
      volumes:
        - name: frontend
          hostPath:
            path: /path/to/index.html
